### ISSUE TITLE
Provide file tree for bigger archives

### ISSUE THREAD

**Issue by Kristine1975** [OldTimes-Software/thedatadungeon.com#3]
**Is your feature request related to a problem? Please describe.**
It's (admittedly only mildly) frustrating to download a large archive and then realize it doesn't contain anything I'm interested in, e.g. it doesn't contain any source code.

**Describe the solution you'd like**
A link next to the link to the archive to a text file that contains the output of `7z l <archive>`. For example:

> [SFM Internal Beta Complete.zip](https://archive.thedatadungeon.com/source_filmmaker_2012/builds/incomplete_beta/sfm_internal_beta_complete.zip) ([file list](https://archive.thedatadungeon.com/source_filmmaker_2012/builds/incomplete_beta/sfm_internal_beta_complete.txt))

Or (simpler) a text file along with the archive with the same content:

> [SFM Internal Beta Complete.zip](https://archive.thedatadungeon.com/source_filmmaker_2012/builds/incomplete_beta/sfm_internal_beta_complete.zip)
> [SFM Internal Beta Complete.files.txt](https://archive.thedatadungeon.com/source_filmmaker_2012/builds/incomplete_beta/sfm_internal_beta_complete.txt)

**Describe alternatives you've considered**
An alternative would be to make cURL download only the end of the archive, and then extract the list of files from the table of contents.

**Comment by hogsy** [comment]
Thanks for the suggestion! This was actually already something we were planning fortunately 😄 
We'll probably throw up a public roadmap at some stage.

**Comment by hogsy** [comment]
Since our plan is a little longer-term, I've just thrown together a different solution so we can get this solved a little sooner.

![image](https://user-images.githubusercontent.com/1946366/206868093-765c594e-d8d2-4f1b-92a3-8d5b35c19ae2.png)

![image](https://user-images.githubusercontent.com/1946366/206868109-31ce5c16-5493-4f0d-b2df-4379f4d1452d.png)

We're using our own tooling to handle packages for now, which on the plus supports more obscure formats but on the down doesn't yet support 7z / rar, so that's something I'll look into at some stage.

**Comment by hogsy** [comment]
That's been rolled out now, I also changed how the information is presented in the content files just to be a little clearer. It's not perfect but we'll improve on this overtime. Thanks again for the feedback!
